name: mirror docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/mirror-docker.yaml"
      - package.json
      - yarn.lock
  schedule:
    - cron: "*/30 * * * *"

jobs:
  dockerhub-mirror:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { src: 'ghcr.io/bangumi/private-server', dest: "trim21/bangumi-private-server", tags: "^(latest|master|master-.*|v.*)$" }
          - { src: 'ghcr.io/bangumi/ms-timeline', dest: "trim21/bangumi-ms-timeline", tags: "^(latest|master|master-.*|v.*)$" }
          - { src: 'ghcr.io/bangumi/chii', dest: "trim21/bangumi-chii", tags: "^(latest|master|master-.*|v.*)$" }
          - { src: 'ghcr.io/trim21/flexget', dest: "trim21/flexget", tags: ".*" }
          - { src: 'ghcr.io/trim21/cactbot-importer', dest: "trim21/cactbot-importer", tags: "^latest$" }
          - { src: 'ghcr.io/trim21/bangumi-workers', dest: "trim21/bangumi-workers", tags: "^latest$" }

    name: "mirror ${{ matrix.dest }}"

    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: trim21
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: |
          wget -O try_linux_amd64.tar.gz https://github.com/trim21/try/releases/download/v0.0.16/try_linux_amd64.tar.gz
          tar xvf try_linux_amd64.tar.gz

      - run: |
          ./try -- wget https://github.com/trim21/imagesync/releases/download/v0.0.4/imagesync_linux_amd64.tar.gz
          tar xvf imagesync_linux_amd64.tar.gz

      - run: |
          ./try --limit=3 --delay=3s -- \
              ./imagesync --override --tags-pattern '${{ matrix.tags }}' --max-concurrent-tags 4 --src "${{ matrix.src }}" --dest "${{ matrix.dest }}"
