name: mirror-gcr-io

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/mirror-gcr-io.yaml
  schedule:
    - cron: "0 */3 * * *"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          docker create --name cadvisor gcr.io/cadvisor/cadvisor:latest
          docker export cadvisor | docker import - ghcr.io/trim21/cadvisor:latest

      - run: echo $DOCKER_TOKEN | docker login ghcr.io -u bangumi --password-stdin
        name: docker login
        env:
          DOCKER_TOKEN: ${{ github.token }}

      - run: |
          docker push "ghcr.io/trim21/cadvisor:latest"
