name: mirror docker image

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  dockerhub-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: trim21
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: docker pull ghcr.io/bangumi/graphql:latest
      - run: docker tag ghcr.io/bangumi/graphql:latest trim21/bangumi-graphql:latest
      - run: docker push trim21/bangumi-graphql:latest
