name: mirror docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/mirror-docker.yaml"
      - package.json
      - yarn.lock
  schedule:
    - cron: "*/30 * * * *"

jobs:
  dockerhub-mirror:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { src: 'ghcr.io/bangumi/private-server', dest: "trim21/bangumi-private-server", tags: "^(master|latest)$"  }
          - { src: 'ghcr.io/bangumi/ms-timeline', dest: "trim21/bangumi-ms-timeline", tags: "^(master|latest)$" }
          - { src: 'ghcr.io/bangumi/chii', dest: "trim21/bangumi-chii", tags: "^(master|latest)$" }

    name: "mirror ${{ matrix.dest }}"

    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: trim21
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: |
          wget https://github.com/trim21/imagesync/releases/download/v0.0.1/imagesync_linux_amd64.tar.gz
          tar xvf imagesync_linux_amd64.tar.gz

      - run: |
          latest=$(curl https://api.github.com/repos/trim21/try/releases/latest | jq '.assets[] | select (.name == "try_linux_amd64.tar.gz") | .browser_download_url' -r)
          wget -O try_linux_amd64.tar.gz ${latest}
          tar xvf try_linux_amd64.tar.gz

      - run: ./try --limit=3 -- ./imagesync -s "${{ matrix.src }}" -d "${{ matrix.dest }}" --tags-pattern '${{ matrix.tags }}';
