name: renovate

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/renovate.yaml"
      - "common/version.sh"
  schedule:
    - cron: "0 */3 * * *"
  repository_dispatch:
    types:
      - renovate

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/setup-python@v2
#         with:
#           python-version: "3.7"

      - name: Get Latest tools version
        id: get-version
        run: bash ./common/version.sh
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - uses: Trim21/setup-poetry@dist/v1

      - run: echo "::set-env name=RENOVATE::$(npm info renovate --json | jq -r .version)"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: renovate-app-14-${{ env.RENOVATE }}
          restore-keys: |
            renovate-app-14-

      - name: Install Renovate cli
        run: npm i renovate

      - run: |
          echo "::set-env name=Y::$(date "+%Y")"
          echo "::set-env name=M::$(date "+%m")"
          echo "::set-env name=D::$(date "+%d")"
          echo "::set-env name=H::$(date "+%H")"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Cache Renovate
        uses: actions/cache@v2
        with:
          path: /tmp/renovate
          key: renovate-cache-${{ env.Y }}-${{ env.M }}-${{ env.D }}-${{ env.H }}
          restore-keys: |
            renovate-cache-${{ env.Y }}-${{ env.M }}-${{ env.D }}
            renovate-cache-${{ env.Y }}-${{ env.M }}-
            renovate-cache-${{ env.Y }}-
            renovate-cache-

      - name: Poetry Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/cache
          key: poetry-cache-${{ env.Y }}-${{ env.M }}-${{ env.D }}-${{ env.H }}
          restore-keys: |
            poetry-cache-${{ env.Y }}-${{ env.M }}-${{ env.D }}
            poetry-cache-${{ env.Y }}-${{ env.M }}-
            poetry-cache-${{ env.Y }}-
            poetry-cache-

      - name: Run renovate cli
        run: |
          npx --no-install \
            renovate Trim21/BGmi \
              --include-forks true \
              --token $PERSONAL_GITHUB_TOKEN \
              --platform github \
              --trust-level high \
              --base-dir /tmp/renovate
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          POETRY_VIRTUALENVS_CREATE: false
          LOG_LEVEL: debug
