name: renovate

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/renovate.yaml"
      - "common/version.sh"
  schedule:
    # daily on github default branch
    - cron: "0 */3 * * *"
  repository_dispatch:
    types:
      - renovate

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Get Latest tools version
        id: get-version
        run: bash ./common/version.sh

      - uses: actions/cache@v2
        name: Cache Poetry
        with:
          path: ~/.poetry
          key: poetry-itself-${{ steps.get-version.outputs.poetry }}

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: renovate-${{ steps.get-version.outputs.renovate }}
          restore-keys: |
            renovate-

      - name: Install Renovate cli
        run: npm i renovate

      - name: Run renovate cli
        run: |
          npx --no-install \
            renovate Trim21/BGmi Trim21/BGmi-NG  \
              --include-forks true \
              --token $PERSONAL_GITHUB_TOKEN \
              --platform github \
              --trust-level high \
              --log-level debug
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          POETRY_VIRTUALENVS_CREATE: "false"
