name: renovate

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/renovate.yaml
      - common/version.sh
      - package.json
      - package-lock.json
  schedule:
    - cron: "0 13 * * *"
  repository_dispatch:
    types:
      - renovate

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: npm

      - run: npm i npm -g

      - run: npm ci

      - uses: actions/setup-python@v3

      - name: Get Latest tools version
        id: get-version
        run: bash ./common/version.sh

      - uses: Trim21/setup-poetry@dist/v1

      - run: node common/date.js

      - name: Cache Renovate
        uses: actions/cache@v3
        with:
          path: /tmp/renovate
          key: renovate-cache-${{ env.TODAY }}
          restore-keys: |
            renovate-cache-${{ env.D1 }}
            renovate-cache-${{ env.D2 }}
            renovate-cache-${{ env.Y }}-${{ env.M }}-
            renovate-cache-${{ env.Y }}-
            renovate-cache-

      - name: Poetry Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/cache
          key: poetry-cache-${{ env.TODAY }}
          restore-keys: |
            poetry-cache-${{ env.D1 }}
            poetry-cache-${{ env.D2 }}
            poetry-cache-${{ env.Y }}-${{ env.M }}-
            poetry-cache-${{ env.Y }}-
            poetry-cache-

      - name: Run renovate cli
        run: |
          npx --no-install \
            renovate Trim21/BGmi \
              --include-forks true \
              --token $PERSONAL_GITHUB_TOKEN \
              --platform github \
              --base-dir /tmp/renovate
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          POETRY_VIRTUALENVS_CREATE: false
          LOG_LEVEL: debug
