name: renovate

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/renovate.yaml
      - common/version.sh
      - package.json
      - package-lock.json
  schedule:
    - cron: "0 */3 * * *"
  repository_dispatch:
    types:
      - renovate

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: 'https://registry.npmjs.org'

      - run: npm i npm -g

      - uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: npm-14-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - uses: actions/setup-python@v2

      - name: Get Latest tools version
        id: get-version
        run: bash ./common/version.sh

      - uses: Trim21/setup-poetry@dist/v1

      - run: |
          echo "Y=$(date "+%Y")" >> $GITHUB_ENV
          echo "M=$(date "+%m")" >> $GITHUB_ENV
          echo "D=$(date "+%d")" >> $GITHUB_ENV
          echo "H=$(date "+%H")" >> $GITHUB_ENV

      - name: Cache Renovate
        uses: actions/cache@v2
        with:
          path: /tmp/renovate
          key: renovate-cache-${{ env.Y }}-${{ env.M }}-${{ env.D }}-${{ env.H }}
          restore-keys: |
            renovate-cache-${{ env.Y }}-${{ env.M }}-${{ env.D }}
            renovate-cache-${{ env.Y }}-${{ env.M }}-
            renovate-cache-${{ env.Y }}-
            renovate-cache-

      - name: Poetry Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/cache
          key: poetry-cache-${{ env.Y }}-${{ env.M }}-${{ env.D }}-${{ env.H }}
          restore-keys: |
            poetry-cache-${{ env.Y }}-${{ env.M }}-${{ env.D }}
            poetry-cache-${{ env.Y }}-${{ env.M }}-
            poetry-cache-${{ env.Y }}-
            poetry-cache-

      - name: Run renovate cli
        run: |
          npx --no-install \
            renovate Trim21/BGmi Trim21/BGmi-NG \
              --include-forks true \
              --token $PERSONAL_GITHUB_TOKEN \
              --platform github \
              --base-dir /tmp/renovate
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          POETRY_VIRTUALENVS_CREATE: false
          LOG_LEVEL: debug
