name: renovate-test

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Trim21/renovate
          ref: fix/poetry/lock-file-maintenance

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: 'https://registry.npmjs.org'

      - run: npm i npm -g

      - run: npm i

      - uses: actions/setup-python@v2

      - uses: Trim21/setup-poetry@dist/v1

      - name: Run renovate cli
        run: |
          npm start -- Trim21/poetry-lock-cannot-update \
              --include-forks true \
              --token $PERSONAL_GITHUB_TOKEN \
              --platform github \
              --base-dir /tmp/renovate
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          POETRY_VIRTUALENVS_CREATE: false
          LOG_LEVEL: debug
