name: sync bucket repos

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/sync-scoop-buckets.yaml
      - mirror_scoop_buckets.js
      - package.json
      - package-lock.json
  schedule:
    - cron: "0 0 1 * *"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: npm-14-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: |
          echo "M=$(date "+%m")" >> $GITHUB_ENV
          echo "D=$(date "+%d")" >> $GITHUB_ENV
          echo "H=$(date "+%H")" >> $GITHUB_ENV

      - name: Repos Cache
        uses: actions/cache@v2
        with:
          path: ./repos/
          key: scoop-bucket-${{ env.M }}-${{ env.D }}
          restore-keys: |
            scoop-bucket-${{ env.M }}-

      - name: Run Mirror Script
        run: node mirror_scoop_buckets.js
        env:
          ACCESS_TOKEN: ${{ secrets.GITEE_TOKEN }}
