name: sync bucket repos

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/sync-scoop-buckets.yaml
      - mirror_scoop_buckets.js
      - package.json
      - package-lock.json
  schedule:
    - cron: "0 12 * * *"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - { name: scoop, url: "https://github.com/ScoopInstaller/Scoop" }
          - { name: main, url: "https://github.com/ScoopInstaller/Main" }
          - { name: dorado, url: "https://github.com/chawyehsu/dorado.git" }
#          - { name: everyx, url: "https://github.com/everyx/scoop-bucket" }
          - { name: extras, url: "https://github.com/lukesampson/scoop-extras" }
          - { name: "github-gh", url: "https://github.com/cli/scoop-gh" }
          - { name: "nerd-fonts", url: "https://github.com/matthewjberger/scoop-nerd-fonts" }
          - { name: versions, url: "https://github.com/ScoopInstaller/Versions" }

    runs-on: ubuntu-latest
    name: "sync ${{ matrix.repo.name }}"

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v3
        id: cache
        with:
          path: ./node_modules
          key: npm-16-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: node common/date.js

      - name: Repos Cache
        uses: actions/cache@v3
        with:
          path: ./repos/
          key: scoop-bucket-${{ matrix.repo.name }}-2-${{ env.TODAY }}
          restore-keys: |
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.D1 }}
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.D2 }}
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.Y }}-${{ env.M }}-
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.Y }}-
            scoop-bucket-${{ matrix.repo.name }}-2-

      - name: Run Mirror Script
        run: node mirror_scoop_buckets.js
        env:
          ACCESS_TOKEN: ${{ secrets.GITEE_TOKEN }}
          NAME: ${{ matrix.repo.name }}
          URL: ${{ matrix.repo.url }}
