name: sync bucket repos

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/sync-scoop-buckets.yaml
      - mirror_scoop_buckets.js
      - package.json
      - package-lock.json
  schedule:
    - cron: "0 */3 * * *"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: npm-14-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: python common/date.py

      - name: Repos Cache
        uses: actions/cache@v2
        with:
          path: ./repos/
          key: scoop-bucket-1-${{ env.TODAY }}
          restore-keys: |
            scoop-bucket-1-${{ env.D1 }}
            scoop-bucket-1-${{ env.D2 }}
            scoop-bucket-1-${{ env.Y }}-${{ env.M }}-
            scoop-bucket-1-${{ env.Y }}-
            scoop-bucket-1-

      - name: Run Mirror Script
        run: node mirror_scoop_buckets.js
        env:
          ACCESS_TOKEN: ${{ secrets.GITEE_TOKEN }}
