name: sync bucket repos

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/sync-scoop-buckets.yaml
      - mirror_scoop_buckets.js
      - package.json
      - yarn.lock
  schedule:
    - cron: "5 */3 * * *"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - { name: scoop, url: "https://github.com/ScoopInstaller/Scoop" }
          - { name: main, url: "https://github.com/ScoopInstaller/Main" }
          - { name: dorado, url: "https://github.com/chawyehsu/dorado.git" }
          - { name: extras, url: "https://github.com/lukesampson/scoop-extras" }
          - { name: "github-gh", url: "https://github.com/cli/scoop-gh" }
          - { name: "nerd-fonts", url: "https://github.com/matthewjberger/scoop-nerd-fonts" }
          - { name: versions, url: "https://github.com/ScoopInstaller/Versions" }
          - { name: backit, url: "https://github.com/batkiz/backit.git" }

    runs-on: ubuntu-latest
    name: "sync ${{ matrix.repo.name }}"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: yarn

      - run: yarn

      - run: node common/date.js

      - name: Repos Cache
        uses: actions/cache@v3
        with:
          path: ./repos/
          key: scoop-bucket-${{ matrix.repo.name }}-2-${{ env.TODAY }}
          restore-keys: |
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.D1 }}
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.D2 }}
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.Y }}-${{ env.M }}-
            scoop-bucket-${{ matrix.repo.name }}-2-${{ env.Y }}-
            scoop-bucket-${{ matrix.repo.name }}-2-

      - name: Run Mirror Script
        run: |
          for i in {1..5}; do
            echo "${i}"
            node mirror_scoop_buckets.js && exit 0
            sleep 1
          done
          
          echo "failed after 5 times retry"
          exit 1

        env:
          ACCESS_TOKEN: ${{ secrets.GITEE_TOKEN }}
          NAME: ${{ matrix.repo.name }}
          URL: ${{ matrix.repo.url }}
