name: test

on:
  push:
    branches:
      - "master"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repo: Trim21/Flexget
          ref: patch-2

      ################ node
      - run: docker build -t flexget .
